version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --workers ${GUNICORN_WORKERS}
    
    # --- LIMITES DO WEB (Django) ---
    deploy:
      resources:
        limits:
          cpus: '0.50'    # Usa no máximo metade de 1 núcleo
          memory: 512M    # Trava em 512 MegaBytes (Ideal para Dev)

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=conveniencia_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    # --- LIMITES DO BANCO (Postgres) ---
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M    # O Postgres adora comer RAM, aqui nós colocamos um freio

volumes:
  postgres_data: